
replicaCount: 3

image:
  repository: diquzart/php-webapp
  tag: 20
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: webapp.example.com
      paths: [/]

  tls: []


resources: 
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 20m
     memory: 50Mi

nodeSelector: {}

tolerations: []

affinity: {}

