# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'diquzart/php-webapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: HelmDeploy@0
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'minikube-default-1570435914912'
    namespace: 'default'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: '**/chart'
    releaseName: 'az-pipeline-test'
    recreate: true
    resetValues: true
    force: true
    tillerNamespace: 'kube-system'
